# Generated by Django 5.2.5 on 2025-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
