# Generated by Django 5.2.9 on 2025-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
